version: '3.7'
services:
  db:
    image: mongo
    container_name: ecommerce-mongo
    restart: always
    ports: 
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
